config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
   resources :editers
   resources :engineers
   resources :others

   root 'tops#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

  if user && user.admin?
    can :access, :rails_admin
    can :manage, :all
  end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/editer.rb
class Editer < ApplicationRecord
has_attached_file :image,
  styles: { medium: "655x435", thumb: "200x121"},
  path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
  url: "/system/:class/image/:id.:style.:extension"

validates_attachment_content_type :image, content_type: /image/

end

app/models/engineer.rb
class Engineer < ApplicationRecord
  has_attached_file :image,
  styles: { medium: "655x435", thumb: "200x121"},
  path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
  url: "/system/:class/image/:id.:style.:extension"

  validates_attachment_content_type :image, content_type: /image/

end

app/models/image.rb
class Image < ApplicationRecord



end

app/models/other.rb
class Other < ApplicationRecord
  has_attached_file :image,
  styles: { medium: "655x435", thumb: "200x121"},
  path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
  url: "/system/:class/image/:id.:style.:extension"

  validates_attachment_content_type :image, content_type: /image/
end

app/models/picture.rb
class Picture < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/editers_controller.rb
class EditersController < ApplicationController

  before_action :set_editer, only: [:show, :delete, :update, :edit]

  def index
    @editers = Editer.all
  end

  def new
    @editer = Editer.new
  end

  def create
    @editer = Editer.new(editer_params)

    if @editer.save
      redirect_to editers_path
    else
      render 'new'
  end
end

  def show
    set_editer
  end

  def edit
    set_others
  end

  def update
    set_editer
    @editer.update(editer_params)
  end

  def delete
    set_editer
    @editer.destroy
  end

  private
  def set_editer
    @editer = Editer.find(params[:id])
  end

  def editer_params
    params.require(:editer).permit(:title, :content, :description, :image, :site)
  end
end

app/controllers/engineers_controller.rb
class EngineersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_engineer, only: [:show, :update, :delete, :edit]

  def index
    @engineers = Engineer.all
  end

  def new
    @engineer = Engineer.new
  end

  def create
    @engineer = Engineer.new(engineers_params)

    if @engineer.save
      redirect_to engineers_path

    else
      render 'new'
    end
  end

  def show
    set_engineer
  end

  def edit
    set_engineer
  end

  def update
    set_engineer
    @engineer.update
  end

  def delete
    set_engineer
    @engineer.delete
  end

  private
  def engineers_params
    params.require(:engineer).permit(:title, :description, :content, :image, :site)
  end

  def set_engineer
    @engineer = Engineer.find(params[:id])
  end
end

app/controllers/others_controller.rb
class OthersController < ApplicationController

  before_action :set_others, only: [:edit, :delete, :show, :edit]

  def index
    @others = Other.all
  end

  def new
    @other = Other.new
   end

  def create
    @other = Other.create(others_params)

    if @other.save
      redirect_to others_path
    else
      render 'new'
    end     
  end

  def show
    set_others
  end

  def edit
    set_others
  end

  def delete
    set_others
    @other.delete
  end

  def update
    set_others
    @other.update
  end

  private
  def others_params
    params.require(:other).permit(:title, :content, :description, :site, :image)
  end

  def set_others
    @other = Other.find(params[:id])
  end
 end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/editor_helper.rb
module EditorHelper
end

app/helpers/engineer_helper.rb
module EngineerHelper
end

app/helpers/other_helper.rb
module OtherHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/editers/_form.html.erb
<%= form_for(@editer, { multipart: true })  do |f| %>
<form class="form-horizontal">
  <div class="row">
    <div class="form-group">
      <div class="col-sm-3">
        <%= f.label :タイトル %>
      </div>
      <div class="col-sm-9">
        <%= f.text_field :title, class:"form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-3">
        <%= f.label :企画内容 %>
      </div>
      <div class="col-sm-9">
        <%= f.text_field :description, class:"form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-3">
        <%= f.label :解説 %>
      </div>
      <div class="col-sm-9">
        <%= f.text_area :content, class:"form-control"  %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-3">
        <%= f.label :参考サイト %>
      </div>
      <div class="col-sm-9">
        <%= f.text_field :site, class:"form-control"  %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-1 text-right">
      <%= f.file_field :image %>

      </br>
      <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
    </div>
  </div>
  <% end %>
</div>
</div>
</form>

app/views/editers/edit.html.erb
<div class="container">
  <h1 class="page-header">編集者編集画面</h1>
    <%= render 'form' %>
  </div>

app/views/editers/index.html.erb
<div class="container">
  <h1>As Editer's Work</h1>
  <% if user_signed_in? %>
   <%= link_to '作成', new_editer_path %>
  <% end %>
  <div class="row">
    <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
      <% @editers.each do |editer| %>
      <div class="kiji">
        <p><%= image_tag editer.image(:thumb) %></p>
        <div class="mike">
          <p>
            <h2><%= link_to editer.title, editer_path(editer) %></h2>
          </p>
          <%= editer.description %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/editers/new.html.erb
<div class="container">
<h1 class="page-header">編集者入力画面</h1>
<%= render 'form' %>
</div>

app/views/editers/show.html.erb
<div class="container">
  <div class="col-sm-3"></div>
  <div class="col-sm-6">
    <div class="text-center">
      <h1><%= @editer.title %></h1>
      <p><%= image_tag @editer.image(:medium) %></p>
    </div>
    <div class="text-center">
      <h3>企画内容</h3>
    </div>
    <div class="text-left">
      <%== @editer.description %>
    </div>
    <div class="text-center">
      <h3>個人的解説</h3>
    </div>
    <div class="text-left">
      <%== @editer.content %>
    </br>
      <h4>参考サイト</h4>
      <%= link_to @editer.site, @editer.site, :target => "_blank" %>
    </div>
  </div>
<div class="col-sm-3"></div>
</div>

app/views/engineers/_form.html.erb
<%= form_for(@engineer) do |f| %>
<form class="form-horizontal">
  <div class="row">
    <div class="form-group">
      <div class="col-sm-3">
        <%= f.label :タイトル %>
      </div>
      <div class="col-sm-9">
        <%= f.text_field :title, class:"form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-3">
        <%= f.label :概要 %>
      </div>
      <div class="col-sm-9">
        <%= f.text_field :description, class:"form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-3">
        <%= f.label :解説 %>
      </div>
      <div class="col-sm-9">
        <%= f.text_area :content, class:"form-control input-xxlg"  %>
      </div>
      <div class="form-group">
        <div class="col-sm-3">
          <%= f.label :参考URL %>
        </div>
        <div class="col-sm-9">
          <%= f.text_field :site, class:"form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-3 col-sm-1 text-right">
        <%= f.file_field :image %>
        </br>
        <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
      </div>
    </div>
    <% end %>
  </div>
</div>
</form>

app/views/engineers/index.html.erb
<div class="container">
  <h1>As Engineer's Work</h1>
  <%= link_to '作成', new_engineer_path %>
  <div class="row">
    <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
      <% @engineers.each do |engineer| %>
      <div class="kiji">
        <p><%= image_tag engineer.image(:thumb) %></p>
        <div class="mike">
        <h2><%= link_to engineer.title, engineer_path(engineer) %></h2>
        <%= engineer.description %>
      </div>
      </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/engineers/new.html.erb
<div class="container">
<h1 class="page-header">編集者入力画面</h1>
<%= render 'form' %>
</div>

app/views/engineers/show.html.erb
<div class="container">
  <div class="col-sm-3"></div>
  <div class="col-sm-6">
    <div class="text-center">
      <h1><%= @engineer.title %></h1>
      <p><%= image_tag @engineer.image(:medium) %></p>
    </div>
    <div class="text-center">
      <h3>概要</h3>
    </div>
    <div class="text-left">
      <%== @engineer.description %>
    </div>
    <div class="text-center">
      <h3>感想など</h3>
    </div>
    <div class="text-left">
      <%== @engineer.content %>
    </br>
      <h4>参考サイト</h4>
      <%= link_to @engineer.site, @engineer.site, :target => "_blank" %>
    </div>
  </div>
<div class="col-sm-3"></div>
</div>

app/views/layouts/_footer.html.erb
</br>
<footer class="footer">
  <div class="container">
    <p class="text-muted">明日は18時より開店</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <div class="navbar-header">
          <button class="navbar-toggle" data-toggle="collapse" data-target=".target">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="collapse navbar-collapse target">
            <ul class="nav navbar-nav">
              <li><%= link_to "トップ", root_path %></li>
              <li><%= link_to "編集", editers_path %></li>
              <li><%= link_to "プログラミング", engineers_path %></li>
              <li><%= link_to "その他", others_path %></li>
              <% if user_signed_in? %>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Introduction</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/others/_form.html.erb
<%= form_for(@other) do |f| %>
<form class="form-horizontal">
  <div class="row">
    <div class="form-group">
      <div class="col-sm-3">
        <%= f.label :タイトル %>
      </div>
      <div class="col-sm-9">
        <%= f.text_field :title, class:"form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-3">
        <%= f.label :説明 %>
      </div>
      <div class="col-sm-9">
        <%= f.text_field :description, class:"form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-3">
        <%= f.label :解説 %>
      </div>
      <div class="col-sm-9">
        <%= f.text_area :content, class:"form-control input-xxlg"  %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-1 text-right">
        <%= f.file_field :image %>
      </br>
      <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
    </div>
  </div>
  <% end %>
</div>
</div>
</form>

app/views/others/edit.html.erb
<h1>OTHER編集画面</h1>
<%= render 'new' %>

app/views/others/index.html.erb
<div class="container">
  <h1>Other Works</h1>
  <% if user_signed_in? %>
   <%= link_to '作成', new_other_path %>
  <% end %>
  <div class="row">
    <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
      <% @others.each do |other| %>
      <div class="kiji">
        <p><%= image_tag other.image(:thumb) %></p>
        <div class="mike">
          <p>
            <h2><%= link_to other.title, other_path(other) %></h2>
          </p>
          <%= other.description %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/others/new.html.erb
<div class="container">
<h1>OTHER投稿画面</h1>
<%= render 'form' %>
</div>

app/views/others/show.html.erb
<div class="container">
  <div class="col-sm-3"></div>
  <div class="col-sm-6">
    <div class="text-center">
      <h1><%= @other.title %></h1>
      <p><%= image_tag @other.image(:medium) %></p>
    </div>
    <div class="text-center">
      <h3>概要</h3>
    </div>
    <div class="text-left">
      <%== @other.description %>
    </div>
    <div class="text-center">
      <h3>個人的解説</h3>
    </div>
    <div class="text-left">
      <%== @other.content %>
    </br>
      <h4>参考サイト</h4>
      <%= link_to @other.site, @other.site, :target => "_blank" %>
    </div>
  </div>
<div class="col-sm-3"></div>
</div>

app/views/tops/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <div style="width 20px">
        <img src="<%= asset_path "naito.png" %>" class="img-responsive">
      </div>
    </div>
    <div class="col-sm-6">
      <h1>こんな時に役立ちます？</h1>
      <div class="text">
        <h2>「可愛い妹」の実在を疑う時</h2>
        「俺の妹がこんなに可愛いわけがない」や「エロマンガ先生」を初め、妹萌えというのは常に人気のあるジャンルの一つ。
        でも「三次元の妹がこんなに可愛いはずがない」と思った時、可愛い妹がいる僕の存在はすごく役立ちますよ。
        うちの大学1年生の妹、本当に可愛い。LINEとか返って来ないこともよく
        ありますが、その性格の悪さも含めて本当に可愛いんです。「可愛い妹」という存在がフィクション
        だと思い夢を失いかけた時、それが実在すると信じるに足る話を出来るはず…。
        <h2>幽霊が怖いか仲良くなりたい時</h2>
        　洒落怖を読んで怖くって眠れなくなった時とか、活躍するかもしれません!! 大学で物語の構造分析、特に
        卒論では「なぜ幽霊が見えるのか」ということを研究していたので、八尺様を読んで怖くて眠れない時、もし
        かしたら気休め程度に役立つ可能性もあり。また、逆に怖い話を聞きたい時も役立ちます。背筋をぞっとさせたい
        時なんかに是非とも話をさせてください。でも、こっちは稲川順二みたいに話をする練習をしてことはなく、
        ただ情報として話の内容が頭の中にあるだけなので、よく話の重要な部分やオチを忘れます。

        <h2>くだらない話が聞きたい時</h2>
        　永延とくだらない話を続けることが出来ます。誰の役にも立たない、中身のないくだらない話を。
        家の近くの猫が可愛いとか、 ダッフィーの右手は美味しいのか、とかそんな意味のない話を飽きずに
        何時間も続けられます。話の内容は毒でも薬でもないですが、時間を浪費を考えると、むしろ毒よりです。
        でも、それでも時間が余って仕方ないという人には試してください。

        <h2>困っていること</h2>
         最近、宇宙人の侵略が微妙に怖いです。これまでは地球に来る技術を持った
        宇宙人が、わざわざ侵略して来る可能性はないと思ってた。だって、ずっと進んだ文明に生きる彼らが、
        争いを好むはずがないから。</br>
        でも、別に進化した文明は争いを嫌うって確証はないって気がついた。
        より進んだ文明を持った宇宙人にとって、争いことが平和って考え方もあるのかもしれない。
        争いは嫌うけど、地球人を殺すのは蟻を潰すのと同じ感覚なのかもしれない。
    </div>
  </div>
</div>
</div>